### PR TITLE
Fixed routing for local host

### PR DESCRIPTION
**Pull request by ralexanderdesign**

### CODE REVIEW

**Comment by camdunne** [comment]
this works now gives me an error, is this fix working for your computer? since it worked without the dot for me

**Comment by ralexanderdesign** [comment]
No way really?? That is bizarre.  Okay well in that case I guess it doesn't
matter which way we keep it- just as long as we stay mindful of it and
making sure it stays working once deployed.  You can just scrap that whole
pull request for now then I'd say- I'll just do it in my working copy

**Comment by camdunne** [comment]
nvm it works now

**Comment by ralexanderdesign** [comment]
Haha no way

**Comment by camdunne** [comment]
so bizarre

**Pull request merged**
